[tool.poetry]
name = "lab3"
version = "0.1.0"
description = ""
authors = ["kitanoyoru <kitanoyoru@protonmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
